---
title: "MATLAB.DataPrep"
author: "Keane Flynn"
date: "12/21/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Loading Libraries
```{r}
library(readr)
library(dbplyr)
library(tidyverse)
```

#Import Roach Run Pre-Augmentation Dataset 
```{r}
BACI_RoachRun_Control <- 
  readr::read_csv(file = "VidSync_Files/Porter_BACI_RoachRun_29June2018_Part3.csv",
                  skip = 1,
                  col_names = c("objects", "event", "timecode", "time", "X", "Y", "Z", "pld_error", "projection_error", "nearest_camera_distance", "screen_coordinates")) %>%
  arrange(objects) %>%
  filter(!grepl("Surface_Shots.*", objects)) %>%
  filter(!grepl("^Length.*", event)) %>%
  mutate(subsample = str_extract(objects, "\\d")) %>%
  mutate(index = str_extract(objects, "\\h\\d{1,2}")) %>%
  mutate(species = str_extract(objects, "Omykiss|Okisutch")) %>%
  transform(index = as.numeric(index),
            subsample = as.numeric(subsample)) %>%
  arrange(subsample, index, time) %>%
  select(index, X, Y, Z)
BACI_RoachRun_Control
```

##For Loop Roach Run Pre-Augmentation
```{r}
for (i in 1:19) {
	if (i == 3) {
		next
	}
	filename <- paste("BACI_RoachRun_Control_", toString(i), ".csv", sep="")
	index <- BACI_RoachRun_Control %>%
		filter(index == i) %>%
		select(X, Y, Z) %>%
  	`colnames<-`(NULL) %>%
		write.csv(file = filename, row.names = FALSE) 
	  print(filename)
}
```

#Import Roach Run Augmentation Dataset 
```{r}
BACI_RoachRun_Control <- 
  readr::read_csv(file = "VidSync_Files/Porter_BACI_RoachRun_5July2018_Part1.csv",
                  skip = 1,
                  col_names = c("objects", "event", "timecode", "time", "X", "Y", "Z", "pld_error", "projection_error", "nearest_camera_distance", "screen_coordinates")) %>%
  arrange(objects) %>%
  filter(!grepl("Surface_Shots.*", objects)) %>%
  filter(!grepl("^Length.*", event)) %>%
  mutate(subsample = str_extract(objects, "\\d")) %>%
  mutate(index = str_extract(objects, "\\h\\d{1,2}")) %>%
  mutate(species = str_extract(objects, "Omykiss|Okisutch")) %>%
  filter(!species == "NA") %>%
  transform(index = as.numeric(index),
            subsample = as.numeric(subsample)) %>%
  arrange(subsample, index, time) %>%
  select(index, X, Y, Z) %>%
  arrange(index)
BACI_RoachRun_Control
```

##For Loop Roach Run Augmentation
```{r}
for (i in 1:33) {
	if (i == 3, 13, 20, 26, 31) {
		next
	}
	filename <- paste("BACI_RoachRun_Control_", toString(i), ".csv", sep="")
	index <- BACI_RoachRun_Control %>%
		filter(index == i) %>%
		select(X, Y, Z) %>%
  	`colnames<-`(NULL) %>%
		write.csv(file = filename, row.names = FALSE) 
	  print(filename)
}
```

#Write.CSV prepping for matlab
```{r}
#index1 <- BACI_RoachRun_Control %>%
  #filter(index == 1) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_1.csv", row.names = FALSE)

#index2 <- BACI_RoachRun_Control %>%
  #filter(index == 2) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_2.csv", row.names = FALSE)

#index4 <- BACI_RoachRun_Control %>%
  #filter(index == 4) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_4.csv", row.names = FALSE)

#index5 <- BACI_RoachRun_Control %>%
  #filter(index == 5) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_5.csv", row.names = FALSE)

#index6 <- BACI_RoachRun_Control %>%
  #filter(index == 6) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_6.csv", row.names = FALSE)

#index7 <- BACI_RoachRun_Control %>%
  #filter(index == 7) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_7.csv", row.names = FALSE)

#index8 <- BACI_RoachRun_Control %>%
  #filter(index == 8) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_8.csv", row.names = FALSE)

#index9 <- BACI_RoachRun_Control %>%
  #filter(index == 9) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_9.csv", row.names = FALSE)

#index10 <- BACI_RoachRun_Control %>%
  #filter(index == 10) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_10.csv", row.names = FALSE)

#index11 <- BACI_RoachRun_Control %>%
  #filter(index == 11) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_11.csv", row.names = FALSE)

#index12 <- BACI_RoachRun_Control %>%
  #filter(index == 12) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_12.csv", row.names = FALSE)

#index13 <- BACI_RoachRun_Control %>%
  #filter(index == 13) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_13.csv", row.names = FALSE)

#index14 <- BACI_RoachRun_Control %>%
  #filter(index == 14) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_14.csv", row.names = FALSE)
#index15 <- BACI_RoachRun_Control %>%
  #filter(index == 15) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_15.csv", row.names = FALSE)

#index16 <- BACI_RoachRun_Control %>%
  #filter(index == 16) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_16.csv", row.names = FALSE)

#index17 <- BACI_RoachRun_Control %>%
  #filter(index == 17) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_17.csv", row.names = FALSE)

#index18 <- BACI_RoachRun_Control %>%
  #filter(index == 18) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_18.csv", row.names = FALSE)

#index19 <- BACI_RoachRun_Control %>%
  #filter(index == 19) %>%
  #select(X, Y, Z) %>%
  #`colnames<-`(NULL) %>%
  #write.csv(file = "BACI_RoachRun_Control_19.csv", row.names = FALSE)
```
